apiVersion: v1
kind: Service
metadata:
  name: scoring-service
  labels:
    app: scoring-service
spec:
  type: LoadBalancer
  selector:
    app: scoring-service
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
