apiVersion: v1
kind: ServiceAccount
metadata:
  name: scoring-sa
  # annotate with IRSA role if using IRSA. Replace if you create the role:
  # annotations:
  #   eks.amazonaws.com/role-arn: arn:aws:iam::REPLACE_AWS_ACCOUNT_ID:role/scoring-service-role
